# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('A', 'Administrador'), ('O', 'Operador')], max_length=1),
        ),
    ]
